import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

const Home: NextPage = ({ data }: any) => {
  console.log(data)

  const handleCheckProductDetail = (id: number) => {
    console.log(id)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container'>
        {data?.products?.map((product: any) => {
          return (
            <div
              className='card'
              key={product?.id}
              onClick={() => handleCheckProductDetail(product.id)}
            >
              <Image
                width={218}
                height={218}
                src={product.thumbnail}
                alt='img'
                style={{
                  objectFit: "cover",
                  borderRadius: "8px",
                }}
              />
              <h5>{product?.discountPercentage}</h5>
              <h5>{product?.price}</h5>
              <h5>{product?.rate}</h5>

              <h5>{product?.title}</h5>
              <h5>{product?.description}</h5>
            </div>
          )
        })}
      </div>
    </div>
  )
}

export default Home

export async function getStaticProps(context: any) {
  const URL = "https://dummyjson.com/products"
  const resp = await fetch(URL)
  const data = await resp.json()

  return {
    props: {
      data,
    },
  }
}
